In [3]:
import pandas as pd

In [2]:
df = pd.read_csv("dummy_data.csv")
df

   id          name                  email   age  country
0   1     Ahmed Ali      ahmed@example.com  25.0    Egypt
1   2  Sara Mohamed       sara@example.com  30.0    Egypt
2   3   Omar Hassan       omar@example.com  22.0    Egypt
3   4     Mona Adel       mona@example.com  28.0    Egypt
4   5  Youssef Samy    youssef@example.com  35.0    Egypt
5   6           Eid  mohammedeid@gmail.com   NaN  America

In [3]:
df = pd.read_csv("dummy_data.csv", usecols=["name", "email"])
df

           name                  email
0     Ahmed Ali      ahmed@example.com
1  Sara Mohamed       sara@example.com
2   Omar Hassan       omar@example.com
3     Mona Adel       mona@example.com
4  Youssef Samy    youssef@example.com
5           Eid  mohammedeid@gmail.com

In [4]:
df = pd.read_csv("dummy_data.csv", index_col="id")
df

            name                  email   age  country
id
1      Ahmed Ali      ahmed@example.com  25.0    Egypt
2   Sara Mohamed       sara@example.com  30.0    Egypt
3    Omar Hassan       omar@example.com  22.0    Egypt
4      Mona Adel       mona@example.com  28.0    Egypt
5   Youssef Samy    youssef@example.com  35.0    Egypt
6            Eid  mohammedeid@gmail.com   NaN  America

In [5]:
df = pd.read_csv("dummy_data.csv", na_values=["N/A", "unknwon"])
df

   id          name                  email   age  country
0   1     Ahmed Ali      ahmed@example.com  25.0    Egypt
1   2  Sara Mohamed       sara@example.com  30.0    Egypt
2   3   Omar Hassan       omar@example.com  22.0    Egypt
3   4     Mona Adel       mona@example.com  28.0    Egypt
4   5  Youssef Samy    youssef@example.com  35.0    Egypt
5   6           Eid  mohammedeid@gmail.com   NaN  America

In [4]:
scores = {"Name": ['a','b','c','d','e'],"score": [195,56,42,41,72]}

df = pd.DataFrame(scores)
df

  Name  score
0    a    195
1    b     56
2    c     42
3    d     41
4    e     72

In [6]:
df1 = df.to_csv("my name.csv")
df1 = pd.read_csv("my name.csv")
df1

   Unnamed: 0 Name  score
0           0    a    195
1           1    b     56
2           2    c     42
3           3    d     41
4           4    e     72

In [7]:
df1 = df.to_csv("my name.csv", index = False)
df1 = pd.read_csv("my name.csv")
df1

  Name  score
0    a    195
1    b     56
2    c     42
3    d     41
4    e     72

In [9]:
df2 = df1.loc[1:3]
df2

  Name  score
1    b     56
2    c     42
3    d     41

In [11]:
df2 = df1.iloc[0:2, 1]
df2

0    195
1     56
Name: score, dtype: int64

In [14]:
df2 = df1.iloc[2, 1]
df2

np.int64(42)