In [2]:
import pandas as pd

# reading csv file 
df = pd.read_csv("people_data.csv")
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

1*2*3

In [2]:
import pandas as pd 
df = pd.read_csv("people_data.csv")
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

# Syntax: pd.read_csv(filepath_or_buffer, sep=' ,' , header='infer',  index_col=None, usecols=None, engine=None, skiprows=None, nrows=None) 

# Parameters: 

# filepath_or_buffer: Location of the csv file. It accepts any string path or URL of the file.
# sep: It stands for separator, default is ', '.
# header: It accepts int, a list of int, row numbers to use as the column names, and the start of the data. If no names are passed, i.e., header=None, then, it will display the first column as 0, the second as 1, and so on.
#usecols: Retrieves only selected columns from the CSV file.
# nrows: Number of rows to be displayed from the dataset.
# index_col: If None, there are no index numbers displayed along with records.  
# skiprows: Skips passed rows in the new data frame.

In [4]:
# The usecols parameter allows to load only specific columns from a CSV file. 
#This reduces memory usage and processing time by importing only the required data.

In [79]:
df = pd.read_csv("people_data.csv", usecols=["First Name", "Email"])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

In [6]:
#The index_col parameter sets one or more columns as the DataFrame index, 
#making the specified column(s) act as row labels for easier data referencing.
df = pd.read_csv("people_data.csv", index_col="First Name")
df

,Last Name,Sex,Email,Date of birth,Job Title
First Name,,,,,
Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [10]:
#The na_values parameter replaces specified strings (e.g., "N/A", "Unknown") with NaN, 
#enabling consistent handling of missing or incomplete data during analysis.\


df = pd.read_csv("people_data.csv", na_values=["N/A", "Unknown"])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [ ]:
# Reading CSV Files with Different Delimiters

In [11]:
#In this example, we will take a CSV file and then add some special characters to see how the sep parameter works.


import pandas as pd

# Sample data stored in a multi-line string
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

# Save the data to a CSV file
with open("sample.csv", "w") as file:
    file.write(data)
print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4

In [12]:
#The sample data is stored in a multi-line string for demonstration purposes.

#Separator (sep): The sep='[:, |_]' argument allows Pandas to handle multiple delimiters (:, |, _, ,) using a regular expression.
#Engine: The engine='python' argument is used because the default C engine does not support regular expressions for delimiters.

In [15]:
#The nrows parameter limits the number of rows read from a file, 
#enabling quick previews or partial data loading for large datasets. Here, we just display only 5 rows using nrows parameter.


df = pd.read_csv('people_data.csv', nrows=3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

# Creating a Sample DataFrame

In [76]:
s = { 'First Name': ['A', 'B', 'C', 'D'], 
    'Last Name': ['E', 'F', 'G', 'FF'], 
     'Age': [10, 20, 30, 40]
        }
import pandas as pd
df = pd.DataFrame(s)
df = df.to_csv('df-csv.csv', index=False)
df = pd.read_csv('df-csv.csv')
df

  First Name Last Name  Age
0          A         E   10
1          B         F   20
2          C         G   30
3          D        FF   40

In [69]:
import pandas as pd
scores = {'Name': ['a', 'b', 'c', 'd'],
          'Score': [90, 80, 95, 20]}
df = pd.DataFrame(scores)
df

  Name  Score
0    a     90
1    b     80
2    c     95
3    d     20

# 1. Basic Export

In [60]:
df = df.to_csv("your_name.csv")
df = pd.read_csv("your_name.csv")
df

   Unnamed: 0 Name  Score
0           0    a     90
1           1    b     80
2           2    c     95
3           3    d     20

# 2. Remove Index Column

In [63]:
df1 = df.to_csv('your_name.csv', index = False)
df1 = pd.read_csv("your_name.csv")
df1

   Unnamed: 0 Name  Score
0           0    a     90
1           1    b     80
2           2    c     95
3           3    d     20

# Export only selected columns

In [64]:
df = df.to_csv("your_name.csv", columns = ['Name'])
df = pd.read_csv("your_name.csv")
df

   Unnamed: 0 Name
0           0    a
1           1    b
2           2    c
3           3    d

# Exclude Header Row

In [65]:
df = df.to_csv('your_name.csv', header = False)
df = pd.read_csv("your_name.csv")
df

   0  0.1  a
0  1    1  b
1  2    2  c
2  3    3  d

# 6. Change Column Separator

In [80]:
df = pd.read_csv('people_data.csv')
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [103]:
x = df.loc[   0:3 , :   ]
type(x)
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher

In [114]:
x = df[df['Date of birth']>1945-10-26].iloc[:, 1:3]
x

TypeError: '>' not supported between instances of 'str' and 'int'

In [81]:
y = [1,2,34]
y[:]

[1, 2, 34]

In [28]:
x = df.iloc[  : , 2:3   ]
x

      Sex
0    Male
1  Female
2    Male
3    Male
4    Male

In [75]:
x = df.iloc[:, 0:2]
x

  First Name Last Name
0     Shelby   Terrell
1    Phillip   Summers
2   Kristine    Travis
3    Yesenia  Martinez
4       Lori      Todd

In [31]:
x = df.iloc[0:2, 0:3]
x

  First Name Last Name     Sex
0     Shelby   Terrell    Male
1    Phillip   Summers  Female

In [30]:
x = df.iloc[  1 , 2  ]
x

'Female'

In [79]:
x = df.iloc[0,1]
x

'Terrell'

In [41]:
x = df[df['Sex']=='Male']
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [83]:
x = df[df['Sex'] == 'Male']
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [48]:
x = df[df['Sex'] == 'Male'].iloc[:, 0:1] 
x

  First Name
0     Shelby
2   Kristine
3    Yesenia
4       Lori

In [101]:
x = df.loc[0:1, :]
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist

In [46]:
x = df.loc[1:2]
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

In [122]:
x = df[(df['Sex'] == 'Male') & (df['Job Title'] == 'Homeopath')] 
x

  First Name Last Name   Sex                  Email Date of birth  Job Title
2   Kristine    Travis  Male  bthompson@example.com    1992-07-02  Homeopath

In [53]:
x = df[(df['Sex'] == 'Male') | (df['Job Title'] == 'Homeopath')] 
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [54]:
x = df[(df['Sex'] == 'Male') & (df['Job Title'] == 'Homeopath') | (df['Date of birth'] == '1945-10-26') ] 
x

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

In [58]:
df['Date of birth'] = pd.to_datetime(df['Date of birth'], dayfirst, yearfirst)
df['Date of birth']
df[df['Date of birth']>'1945-10-26']

,First Name,Last Name,Sex,Email,Date of birth,Job Title
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher

In [117]:
df['Sex'] == 'Male'

0     True
1    False
2     True
3     True
4     True
Name: Sex, dtype: bool

In [119]:
(2==2) and (3==3)

True

In [120]:
1 & 1

1