In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("apple_products_dataset_100k.csv")
df.head()

,product_id,category,model_name,release_year,price,rating,color,storage,ram,cpu,gpu,screen_size,battery_mAh,weight_grams,dimensions_mm,warranty,country_origin,seller_id,in_stock,review_count
0,P000001,iMac,Model-754,2019,1519.71,4.6,Space Gray,256GB,4GB,A16 Bionic,M-Series GPU,"6.7""",6181,1103,92x159x19,6 Months,India,S8196,True,2189
1,P000002,AirPods,Model-214,2019,1124.86,3.5,Red,1TB,4GB,A14 Bionic,M-Series GPU,"6.1""",8085,1687,153x102x38,1 Year,USA,S6264,True,259
2,P000003,MacBook,Model-125,2016,1877.50,2.9,Silver,1TB,16GB,A15 Bionic,M-Series GPU,"5.4""",6359,2311,220x150x31,2 Years,India,S9930,False,3078
3,P000004,AirPods,Model-859,2019,1475.74,2.1,Silver,512GB,8GB,A15 Bionic,Integrated,"16""",4857,1966,174x270x19,2 Years,USA,S2204,False,4929
4,P000005,AirPods,Model-381,2017,3108.82,3.4,Blue,512GB,4GB,A15 Bionic,Apple GPU,"13.3""",10785,2039,276x164x5,2 Years,China,S4957,True,2995

In [6]:
df.tail()

,product_id,category,model_name,release_year,price,rating,color,storage,ram,cpu,gpu,screen_size,battery_mAh,weight_grams,dimensions_mm,warranty,country_origin,seller_id,in_stock,review_count
99995,P099996,Apple Watch,Model-409,2017,1215.27,5.0,Space Gray,32GB,8GB,M3,Integrated,"6.1""",6223,1501,377x218x15,1 Year,India,S5717,True,1693
99996,P099997,AirPods,Model-701,2015,887.88,3.0,Blue,512GB,32GB,M3,Apple GPU,"16""",11048,2945,176x128x22,2 Years,Germany,S2175,True,651
99997,P099998,iMac,Model-571,2015,2303.21,4.6,Space Gray,1TB,8GB,M2,Apple GPU,"13.3""",1568,1048,129x95x31,6 Months,UK,S9092,True,3916
99998,P099999,iPhone,Model-951,2019,1166.86,3.2,White,128GB,16GB,A16 Bionic,Apple GPU,"6.7""",3315,1764,274x90x35,6 Months,Germany,S6981,True,287
99999,P100000,iMac,Model-400,2017,2149.45,4.7,Gold,1TB,6GB,A16 Bionic,Apple GPU,"10.2""",8088,2053,214x168x24,6 Months,Japan,S1057,True,4864

In [9]:
df.describe()

,release_year,price,rating,battery_mAh,weight_grams,review_count
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2019.487210,1902.278098,2.997510,6768.332740,1598.315840,2500.821250
std,2.875465,925.079772,1.156889,3033.377945,807.638303,1441.585681
min,2015.000000,300.030000,1.000000,1500.000000,200.000000,0.000000
25%,2017.000000,1098.507500,2.000000,4135.000000,898.000000,1253.000000
50%,2019.000000,1903.405000,3.000000,6779.000000,1597.000000,2499.000000
75%,2022.000000,2704.225000,4.000000,9397.000000,2299.000000,3747.000000
max,2024.000000,3499.950000,5.000000,11999.000000,2999.000000,4999.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   product_id      100000 non-null  object
 1   category        100000 non-null  object
 2   model_name      100000 non-null  object
 3   release_year    100000 non-null  int64
 4   price           100000 non-null  float64
 5   rating          100000 non-null  float64
 6   color           100000 non-null  object
 7   storage         100000 non-null  object
 8   ram             100000 non-null  object
 9   cpu             100000 non-null  object
 10  gpu             100000 non-null  object
 11  screen_size     100000 non-null  object
 12  battery_mAh     100000 non-null  int64
 13  weight_grams    100000 non-null  int64
 14  dimensions_mm   100000 non-null  object
 15  warranty        100000 non-null  object
 16  country_origin  100000 non-null  object
 17  seller_id       100000 non-null  object
 18  in_stock        100000 non-null  bool
 19  review_count    100000 non-null  int64
dtypes: bool(1), float64(2), int64(4), object(13)
memory usage: 14.6+ MB

In [10]:
df.iloc[1:4, 3:5]

   release_year    price
1          2019  1124.86
2          2016  1877.50
3          2019  1475.74

In [11]:
df.loc[3:8]

,product_id,category,model_name,release_year,price,rating,color,storage,ram,cpu,gpu,screen_size,battery_mAh,weight_grams,dimensions_mm,warranty,country_origin,seller_id,in_stock,review_count
3,P000004,AirPods,Model-859,2019,1475.74,2.1,Silver,512GB,8GB,A15 Bionic,Integrated,"16""",4857,1966,174x270x19,2 Years,USA,S2204,False,4929
4,P000005,AirPods,Model-381,2017,3108.82,3.4,Blue,512GB,4GB,A15 Bionic,Apple GPU,"13.3""",10785,2039,276x164x5,2 Years,China,S4957,True,2995
5,P000006,iPad,Model-350,2021,1908.07,2.0,Red,32GB,8GB,A16 Bionic,Apple GPU,"16""",10629,288,154x117x26,1 Year,USA,S9347,True,3333
6,P000007,MacBook,Model-328,2023,3460.40,1.5,Blue,64GB,4GB,A14 Bionic,Apple GPU,"16""",9241,629,135x283x10,2 Years,Japan,S8297,True,4424
7,P000008,MacBook,Model-242,2024,2767.65,4.6,White,64GB,16GB,M3,Apple GPU,"5.4""",3284,2744,314x221x13,1 Year,USA,S8044,True,3137
8,P000009,MacBook,Model-854,2020,714.59,4.6,Blue,2TB,16GB,A14 Bionic,Apple GPU,"16""",4614,1127,114x90x40,6 Months,Germany,S3656,True,2034

In [13]:
df["price"]

0        1519.71
1        1124.86
2        1877.50
3        1475.74
4        3108.82
          ...
99995    1215.27
99996     887.88
99997    2303.21
99998    1166.86
99999    2149.45
Name: price, Length: 100000, dtype: float64

In [14]:
type(df["price"])

pandas.core.series.Series

In [17]:
df["price"] >2000

0        False
1        False
2        False
3        False
4         True
         ...
99995    False
99996    False
99997     True
99998    False
99999     True
Name: price, Length: 100000, dtype: bool

In [18]:
type(df["price"] >2000)

pandas.core.series.Series

In [ ]:
df[df["price"] >3499]

In [29]:
type(df[df["price"] >3499])

pandas.core.frame.DataFrame

In [36]:
df[df["price"] >3499][["price","category"]]

         price     category
718    3499.24       iPhone
6771   3499.24         iMac
9736   3499.95       iPhone
11721  3499.17      MacBook
13068  3499.61         iPad
15037  3499.88      AirPods
21277  3499.77         iMac
21998  3499.85         iPad
25643  3499.50  Apple Watch
30671  3499.22       iPhone
30801  3499.62         iPad
35853  3499.44  Apple Watch
36730  3499.51  Apple Watch
41297  3499.16      MacBook
43256  3499.87      AirPods
44645  3499.87       iPhone
45919  3499.20      AirPods
45985  3499.44         iMac
48643  3499.01      MacBook
49920  3499.74       iPhone
54812  3499.78         iMac
58199  3499.52         iMac
58251  3499.37      AirPods
58519  3499.36         iPad
65336  3499.57      AirPods
65718  3499.05         iMac
66486  3499.13       iPhone
68214  3499.69      AirPods
70987  3499.37       iPhone
71480  3499.28       iPhone
76757  3499.47         iMac
78587  3499.81  Apple Watch
81047  3499.91         iPad
88513  3499.58         iMac
88521  3499.43       iPhone

In [6]:
df.loc[df["price"]>3499, ["category", "release_year"]]

          category  release_year
718         iPhone          2017
6771          iMac          2016
9736        iPhone          2024
11721      MacBook          2022
13068         iPad          2023
15037      AirPods          2019
21277         iMac          2019
21998         iPad          2019
25643  Apple Watch          2020
30671       iPhone          2023
30801         iPad          2016
35853  Apple Watch          2019
36730  Apple Watch          2022
41297      MacBook          2016
43256      AirPods          2022
44645       iPhone          2016
45919      AirPods          2024
45985         iMac          2019
48643      MacBook          2021
49920       iPhone          2023
54812         iMac          2019
58199         iMac          2015
58251      AirPods          2017
58519         iPad          2024
65336      AirPods          2024
65718         iMac          2019
66486       iPhone          2015
68214      AirPods          2020
70987       iPhone          2022
71480       iPhone          2018
76757         iMac          2017
78587  Apple Watch          2024
81047         iPad          2016
88513         iMac          2022
88521       iPhone          2017

In [7]:
df[df["model_name"] == "Model-859"]

,product_id,category,model_name,release_year,price,rating,color,storage,ram,cpu,gpu,screen_size,battery_mAh,weight_grams,dimensions_mm,warranty,country_origin,seller_id,in_stock,review_count
3,P000004,AirPods,Model-859,2019,1475.74,2.1,Silver,512GB,8GB,A15 Bionic,Integrated,"16""",4857,1966,174x270x19,2 Years,USA,S2204,False,4929
519,P000520,iPad,Model-859,2019,2038.47,3.9,Red,256GB,32GB,A14 Bionic,M-Series GPU,"6.7""",2328,1329,171x214x35,2 Years,China,S8038,True,2319
649,P000650,MacBook,Model-859,2017,1338.33,2.0,Space Gray,32GB,16GB,M1,Apple GPU,"6.7""",9594,2071,376x118x21,6 Months,Japan,S1791,True,3767
1826,P001827,AirPods,Model-859,2021,1570.17,1.5,Blue,32GB,32GB,A15 Bionic,M-Series GPU,"13.3""",4800,1282,294x83x11,6 Months,Japan,S2452,True,1061
2091,P002092,iMac,Model-859,2024,1300.03,2.4,Space Gray,256GB,4GB,A16 Bionic,Apple GPU,"6.1""",8404,2363,365x288x27,1 Year,China,S6460,True,3265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96864,P096865,MacBook,Model-859,2020,3395.77,4.3,Blue,512GB,6GB,A14 Bionic,M-Series GPU,"13.3""",3998,925,137x249x32,1 Year,UK,S8298,True,4556
96988,P096989,MacBook,Model-859,2017,1577.57,1.1,Silver,128GB,6GB,M1,Integrated,"13.3""",5322,751,278x289x23,1 Year,Japan,S7672,True,969
97409,P097410,AirPods,Model-859,2017,3305.63,1.0,Blue,1TB,4GB,A15 Bionic,Apple GPU,"10.2""",3156,2643,349x121x16,6 Months,India,S3493,True,1484
99534,P099535,iMac,Model-859,2017,2294.78,3.9,Silver,32GB,32GB,M1,Apple GPU,"5.4""",6761,729,301x263x6,2 Years,UK,S8717,True,1739
99538,P099539,MacBook,Model-859,2021,1737.16,1.9,Blue,64GB,6GB,A14 Bionic,Integrated,"13.3""",6511,1204,257x224x25,2 Years,USA,S6208,True,4869

In [8]:
df.groupby("rating")

In [12]:
df.groupby("rating", sort = True).sum()

,product_id,category,model_name,release_year,price,color,storage,ram,cpu,gpu,screen_size,battery_mAh,weight_grams,dimensions_mm,warranty,country_origin,seller_id,in_stock,review_count
rating,,,,,,,,,,,,,,,,,,,
1.0,P000250P000255P000474P000728P000941P000945P001...,iMaciPadiPhoneMacBookiMaciPadiPhoneiMaciMacApp...,Model-775Model-640Model-769Model-125Model-720M...,2595051,2507424.85,Space GrayWhiteWhiteBlueWhiteBlueGoldBlueRedRe...,32GB64GB1TB128GB128GB32GB32GB1TB512GB512GB128G...,4GB6GB16GB16GB4GB8GB4GB4GB8GB6GB32GB6GB16GB8GB...,M1A15 BionicA16 BionicA16 BionicM3M2M3M2A16 Bi...,M-Series GPUIntegratedM-Series GPUM-Series GPU...,"6.1""5.4""5.4""10.2""6.7""6.7""13.3""6.7""6.1""6.7""16""1...",8597244,2025534,302x202x10381x251x9219x77x7384x106x21208x160x5...,1 Year2 Years6 Months6 Months1 Year6 Months6 M...,GermanyUKGermanyUSAUSAUKUKUSAUKChinaGermanyUSA...,S9126S4863S5923S6094S9061S7130S2128S5952S9791S...,1067,3227759
1.1,P000068P000210P000229P000271P000277P000288P000...,iMaciPadiMacMacBookiPhoneMacBookiMaciMaciPhone...,Model-400Model-405Model-471Model-548Model-165M...,5004330,4715115.96,SilverSilverGoldWhiteRedBlackWhiteBlackSilverB...,1TB64GB256GB512GB1TB128GB1TB64GB64GB32GB256GB2...,6GB6GB6GB4GB8GB16GB4GB16GB4GB4GB16GB16GB4GB16G...,M2A16 BionicA16 BionicM1M1M3M3A14 BionicM2M3M1...,M-Series GPUIntegratedIntegratedIntegratedAppl...,"6.1""14""14""13.3""14""10.2""6.1""10.2""6.7""5.4""10.2""1...",16987449,3990367,231x171x5274x95x23174x288x18202x138x24110x81x5...,1 Year2 Years1 Year6 Months2 Years1 Year1 Year...,USAUSAGermanyJapanChinaIndiaIndiaIndiaUKUKIndi...,S1503S4518S2220S1185S4989S6900S2547S6971S5771S...,2160,6243833
1.2,P000055P000103P000108P000146P000286P000396P000...,iPadiPhoneMacBookiPhoneiPhoneiPadiPhoneMacBook...,Model-967Model-173Model-846Model-352Model-172M...,5196408,4891389.15,BlueBlueBlueBlackRedBlackGoldGoldBlackRedGoldS...,64GB1TB128GB2TB1TB256GB32GB32GB1TB2TB128GB32GB...,4GB32GB6GB32GB32GB32GB16GB16GB6GB32GB6GB16GB8G...,A15 BionicA16 BionicA15 BionicA14 BionicM2A14 ...,Apple GPUApple GPUIntegratedApple GPUApple GPU...,"5.4""14""5.4""13.3""10.2""10.2""6.1""16""5.4""10.2""6.7""...",17201514,4141381,124x99x39223x282x20207x121x40112x91x6396x201x1...,6 Months1 Year6 Months2 Years1 Year6 Months6 M...,GermanyGermanyUKUSAUSAUKUSAUKChinaUKUSAGermany...,S6909S2613S8858S5705S1977S3850S7544S3260S4972S...,2155,6447018
1.3,P000037P000046P000073P000077P000109P000190P000...,Apple WatchiPhoneiPadiPadiPhoneApple WatchiPad...,Model-990Model-259Model-470Model-171Model-350M...,5008603,4714104.98,SilverBlackBlackRedBlackRedBlackSilverBlackWhi...,512GB2TB2TB64GB2TB64GB256GB2TB512GB64GB64GB256...,16GB4GB8GB8GB32GB16GB8GB4GB4GB4GB8GB8GB16GB32G...,M3A16 BionicM2A16 BionicA15 BionicA15 BionicA1...,IntegratedApple GPUIntegratedIntegratedIntegra...,"13.3""6.1""6.7""5.4""13.3""6.1""6.7""14""6.1""10.2""14""1...",16737034,3935712,363x133x5393x120x33296x152x28227x94x16312x92x2...,2 Years1 Year1 Year2 Years6 Months2 Years1 Yea...,UKJapanIndiaIndiaGermanyJapanJapanUKIndiaJapan...,S9214S4399S7666S5174S3363S7119S5205S7523S6597S...,2107,6157237
1.4,P000036P000057P000059P000118P000137P000141P000...,Apple WatchiPadiMaciMaciPadiPadiMacApple Watch...,Model-928Model-718Model-926Model-801Model-317M...,5145798,4895404.11,SilverGoldSilverBlueBlackBlackSpace GrayBlueWh...,512GB128GB2TB256GB32GB32GB32GB64GB32GB128GB256...,32GB8GB8GB16GB16GB4GB16GB16GB6GB6GB16GB6GB6GB6...,A14 BionicA16 BionicA14 BionicM2M3M2A15 Bionic...,IntegratedM-Series GPUM-Series GPUIntegratedM-...,"5.4""6.7""10.2""5.4""6.1""6.1""6.7""16""5.4""10.2""14""10...",17380482,4086093,384x194x10258x69x8355x60x10356x109x2075x106x34...,2 Years1 Year1 Year6 Months2 Years1 Year6 Mont...,JapanIndiaUKUSAUKGermanyIndiaJapanJapanUKIndia...,S2653S8091S9503S1448S7455S7635S2047S8766S2497S...,2192,6307349
1.5,P000007P000091P000098P000223P000232P000234P000...,MacBookiPadAirPodsiPhoneiMacMacBookMacBookiPad...,Model-328Model-750Model-786Model-100Model-926M...,5135515,4795901.61,BlueBlueGoldSpace GrayGoldBlackBlackBlackBlack...,64GB32GB1TB128GB32GB512GB256GB256GB1TB32GB32GB...,4GB6GB8GB16GB6GB4GB4GB4GB4GB6GB16GB32GB8GB32GB...,A14 BionicA14 BionicM1A15 BionicM3A14 BionicA1...,Apple GPUM-Series GPUApple GPUM-Series GPUAppl...,"16""13.3""6.7""14""5.4""6.7""13.3""5.4""5.4""10.2""14""10...",16999288,4024390,135x283x10303x114x23316x173x34136x185x26339x20...,2 Years1 Year2 Years1 Year2 Years1 Year1 Year2...,JapanUSAJapanChinaJapanGermanyGermanyGermanyUK...,S8297S4781S8578S4419S1491S1182S6399S4044S5313S...,2169,6307340
1.6,P000047P000099P000115P000196P000226P000302P000...,iPadiPhoneiPadMacBookApple WatchiPhoneiMacAirP...,Model-320Model-373Model-804Model-261Model-600M...,5016351,4696589.64,SilverRedBlackSpace GraySilverGoldRedGoldRedBl...,512GB1TB2TB1TB1TB1TB256GB32GB512GB64GB1TB256GB...,16GB6GB32GB16GB8GB16GB4GB6GB32GB4GB8GB8GB6GB6G...,A16 BionicM1A15 BionicA15 BionicA15 BionicM3M2...,Apple GPUM-Series GPUM-Series GPUIntegratedM-S...,"13.3""14""13.3""13.3""6.7""6.1""5.4""6.1""6.7""14""6.7""6...",16616217,3958401,82x186x7190x207x36213x248x14326x132x3163x152x1...,1 Year2 Years2 Years2 Years6 Months1 Year6 Mon...,ChinaUKUSAChinaJapanUKUKUKUKGermanyChinaChinaI...,S6775S8337S2898S1712S9605S5303S6782S9020S1081S...,2102,6084925
1.7,P000041P000102P000127P000203P000208P000251P000...,iPhoneiPhoneApple WatchiPhoneiMaciMacMacBookiP...,Model-263Model-763Model-924Model-612Model-991M...,5056819,4723713.00,RedSilverGoldRedRedSpace GraySilverWhiteSpace ...,512GB32GB1TB1TB32GB512GB512GB1TB64GB64GB256GB2...,6GB4GB6GB32GB8GB32GB8GB4GB6GB4GB4GB32GB16GB8GB...,M3M3M3M2A14 BionicA15 BionicM2A16 BionicM2A15 ...,Apple GPUIntegratedApple GPUIntegratedIntegrat...,"13.3""14""13.3""5.4""6.7""13.3""6.1""10.2""14""10.2""5.4...",17082465,3992712,399x244x37143x142x39381x142x16311x118x37252x29...,6 Months6 Months6 Months1 Year2 Years1 Year6 M...,UKUSAUKUSAUSAChinaIndiaUKJapanGermanyGermanyUK...,S7797S1845S6394S4822S7261S2357S5771S3748S5881S...,2133,6359920
1.8,P000017P000071P000072P000182P000212P000297P000...,Apple WatchApple WatchApple WatchiPhoneiPhoneA...,Model-132Model-733Model-982Model-111Model-754M...,5030420,4784478.67,SilverWhiteBlueRedBlueBlueGoldRedSilverRedRedW...,32GB64GB2TB512GB32GB1TB1TB2TB128GB1TB512GB64GB...,8GB16GB6GB6GB16GB6GB4GB16GB8GB8GB6GB6GB32GB32G...,A15 BionicA15 BionicM3A15 BionicA14 BionicA14 ...,M-Series GPUIntegratedM-Series GPUIntegratedIn...,"13.3""13.3""5.4""6.1""5.4""10.2""14""10.2""10.2""14""5.4...",16801326,3979199,86x241x26199x212x25253x250x34311x95x23313x182x...,6 Months2 Years1 Year1 Year2 Years1 Year2 Year...,UKGermanyUSAIndiaJapanUKGermanyGermanyUKChinaC...,S9297S9351S2587S9425S1295S3671S6950S4695S6459S...,2088,6180920
1.9,P000043P000044P000145P000153P000168P000224P000...,AirPodsMacBookMacBookMacBookiMaciPhoneiMaciPho...,Model-532Model-448Model-242Model-538Model-263M...,5194183,4807220.98,BlackSilverBlueSpace GrayWhiteBlackBlackGoldSp...,32GB256GB64GB256GB1TB32GB64GB32GB512GB1TB2TB32...,4GB32GB6GB16GB8GB4GB8GB6GB32GB16GB32GB32GB16GB...,M3A15 BionicM1M1M3M3M3A16 BionicM3M3M3A16 Bion...,IntegratedIntegratedM-Series GPUIntegratedAppl...,"16""6.1""13.3""5.4""6.7""16""6.1""5.4""5.4""6.7""6.7""6.7...",17480354,4126179,396x134x11215x158x27213x69x1470x218x32310x180x...,2 Years2 Years1 Year6 Months2 Years1 Year1 Yea...,UKGermanyChinaUKGermanyIndiaJapanIndiaUSAGerma...,S5458S5794S5079S6608S8990S7020S2423S7142S6154S...,2175,6419041
2.0,P000006P000016P000042P000100P000124P000184P000...,iPadiMacMacBookAirPodsAirPodsApple WatchMacBoo...,Model-350Model-532Model-814Model-818Model-334M...,5012393,4789037.98,RedWhiteSilverGoldSpace GraySilverBlueWhiteGol...,32GB64GB2TB1TB64GB256GB2TB128GB128GB32GB2TB64G...,8GB8GB8GB6GB16GB32GB6GB6GB32GB32GB6GB4GB4GB6GB...,A16 BionicM2M3M1A15 BionicA16 BionicM1M1M3A16 ...,Apple GPUApple GPUM-Series GPUM-Series GPUM-Se...,"16""16""14""10.2""6.1""13.3""5.4""16""5.4""10.2""6.7""6.1...",16885900,3983762,154x117x26380x207x31112x197x36323x292x28163x20...,1 Year1 Year6 Months6 Months6 Months1 Year2 Ye...,USAIndiaUKUKGermanyUSAGermanyUKChinaUKGermanyG...,S9347S9541S6861S8356S4747S1641S7089S3302S3685S...,2103,6195047
2.1,P000004P000074P000081P000090P000120P000174P000...,AirPodsiMaciPadAirPodsiMacApple WatchiPhoneiPa...,Model-859Model-691Model-891Model-564Model-963M...,4947660,4712543.74,SilverGoldGoldBlackSpace GraySilverWhiteGoldGo...,512GB128GB128GB1TB128GB1TB2TB64GB512GB1TB128GB...,8GB32GB16GB16GB8GB16GB8GB16GB6GB6GB8GB6GB4GB16...,A15 BionicA16 BionicM1A16 BionicM3M2A15 Bionic...,IntegratedApple GPUApple GPUApple GPUM-Series ...,"16""13.3""14""5.4""10.2""10.2""10.2""16""16""14""6.1""13....",16347721,3943968,174x270x19279x293x9280x102x22297x176x37353x234...,2 Years1 Year2 Years1 Year1 Year2 Years2 Years...,USAGermanyUKJapanUSAJapanChinaJapanIndiaChinaI...,S2204S9247S7993S7555S1983S5613S1542S5568S8663S...,2068,6012335
2.2,P000026P000133P000199P000215P000219P000231P000...,AirPodsApple WatchMacBookiPhoneiPadApple Watch...,Model-303Model-680Model-839Model-303Model-265M...,4854781,4562010.50,RedSpace GrayBlueRedGoldGoldSilverSpace GrayRe...,512GB128GB32GB128GB2TB32GB256GB128GB128GB512GB...,16GB4GB6GB6GB4GB4GB6GB8GB4GB16GB6GB16GB16GB4GB...,A15 BionicA15 BionicM3M1M2A16 BionicM2A16 Bion...,Apple GPUIntegratedApple GPUApple GPUApple GPU...,"6.1""10.2""5.4""13.3""16""10.2""16""6.7""10.2""10.2""5.4...",16232465,3849051,192x163x18262x200x20175x69x1580x73x16396x210x3...,2 Years1 Year2 Years1 Year6 Months2 Years2 Yea...,ChinaIndiaUSAGermanyIndiaGermanyIndiaChinaGerm...,S1531S3079S1700S6504S8781S7946S8597S2137S2086S...,2062,5939490
2.3,P000034P000048P000062P000083P000121P000204P000...,iMaciMacAirPodsiMaciPadApple WatchAirPodsMacBo...,Model-703Model-881Model-570Model-181Model-886M...,5076905,4723196.36,BlackRedGoldBlackBlueWhiteRedRedGoldBlackBlack...,2TB256GB64GB256GB32GB64GB2TB512GB512GB2TB32GB3...,32GB4GB16GB32GB6GB6GB8GB4GB6GB4GB4GB16GB8GB6GB...,A14 BionicM1M3M3A14 BionicM1M1M1A16 BionicA14 ...,Apple GPUM-Series GPUIntegratedM-Series GPUInt...,"6.1""13.3""13.3""6.1""13.3""5.4""16""10.2""13.3""16""10....",17005986,3947348,186x250x7383x126x20251x202x11135x250x11111x143...,6 Months2 Years2 Years6 Months6 Months2 Years2...,UKUSAChinaIndiaGermanyGermanyJapanIndiaGermany...,S7731S1895S8759S5556S7484S7362S7465S3332S2173S...,2109,6379807
2.4,P000039P000049P000082P000086P000087P000157P000...,iMaciPhoneApple WatchiMaciPhoneMacBookAirPodsM...,Model-877Model-444Model-396Model-987Model-203M...,4955782,4638408.71,Space GraySpace GrayBlueSpace GraySilverSilver...,64GB128GB64GB32GB128GB2TB512GB256GB256GB256GB2...,32GB4GB16GB6GB6GB16GB16GB16GB16GB16GB32GB6GB8G...,M1M2M3A14 BionicM1A14 BionicA16 BionicA15 Bion...,Apple GPUApple GPUIntegratedIntegratedApple GP...,"13.3""6.1""6.1""5.4""16""6.1""13.3""10.2""5.4""13.3""13....",16659109,3922970,129x210x27387x228x35147x65x11173x125x16155x66x...,6 Months1 Year2 Years1 Year6 Months1 Year6 Mon...,UKGermanyJapanGermanyJapanUSAJapanUSAGermanyGe...,S1429S9516S7964S4395S2398S2677S2434S7402S7418S...,2084,6120022
2.5,P000066P000136P000222P000266P000278P000327P000...,iMacAirPodsAirPodsiPhoneiPadApple WatchApple W...,Model-180Model-422Model-643Model-419Model-446M...,5272791,5080257.67,BlueSpace GrayGoldBlackGoldWhiteBlackRedBlackB...,32GB512GB512GB32GB256GB512GB32GB32GB2TB128GB12...,32GB8GB8GB4GB4GB32GB8GB16GB16GB4GB6GB4GB16GB8G...,M3M1M3A15 BionicA15 BionicA14 BionicA16 Bionic...,Apple GPUIntegratedM-Series GPUM-Series GPUApp...,"5.4""10.2""16""6.1""5.4""14""6.7""5.4""6.7""6.7""16""10.2...",17911566,4171241,89x74x24181x130x24196x95x28323x101x2296x259x28...,2 Years2 Years6 Months1 Year2 Years6 Months6 M...,GermanyUKUKUKUKIndiaUKUSAUSAUSAGermanyUSAIndia...,S2073S8959S5718S5097S6983S3919S6887S2607S1804S...,2213,6561757
2.6,P000177P000209P000214P000235P000253P000293P000...,iMacApple WatchiPhoneiPhoneiMaciMaciPhoneAirPo...,Model-579Model-740Model-723Model-159Model-269M...,5044617,4715613.35,RedSpace GrayGoldRedRedSilverSilverGoldBlackGo...,2TB2TB2TB2TB1TB64GB256GB512GB64GB64GB32GB2TB51...,6GB16GB8GB32GB8GB32GB32GB4GB6GB6GB6GB6GB6GB4GB...,A14 BionicM3M3M2A14 BionicA14 BionicM1A15 Bion...,Apple GPUM-Series GPUM-Series GPUApple GPUInte...,"16""10.2""16""6.7""14""10.2""16""16""5.4""16""13.3""6.1""5...",16857707,3979825,162x270x17214x100x29104x64x37146x124x16382x166...,2 Years6 Months1 Year1 Year6 Months1 Year2 Yea...,UKIndiaJapanUKGermanyChinaJapanUKJapanGermanyJ...,S3980S7960S5836S2081S1798S5749S2514S9316S6788S...,2119,6289081
2.7,P000013P000134P000161P000201P000304P000375P000...,Apple WatchMacBookiPadiPhoneiPhoneiPadApple Wa...,Model-658Model-997Model-193Model-836Model-840M...,5064983,4797361.22,SilverWhiteWhiteBlackWhiteSilverSpace GraySilv...,32GB128GB1TB256GB256GB64GB32GB2TB512GB256GB256...,32GB32GB32GB32GB32GB6GB4GB16GB8GB8GB32GB4GB4GB...,A14 BionicM3A14 BionicM1A16 BionicA14 BionicA1...,M-Series GPUApple GPUApple GPUApple GPUM-Serie...,"6.1""5.4""13.3""6.7""13.3""13.3""16""13.3""6.1""6.7""14""...",17008299,4026587,292x81x6220x73x27158x166x16254x228x39392x91x33...,2 Years1 Year1 Year2 Years1 Year6 Months2 Year...,JapanChinaIndiaChinaJapanUSAUSAIndiaJapanGerma...,S9465S2306S4214S7752S5982S6093S6610S3231S9392S...,2138,6337095
2.8,P000022P000028P000040P000076P000094P000112P000...,iPhoneiPhoneiMacAirPodsiPhoneiPhoneiMacApple W...,Model-617Model-765Model-925Model-821Model-266M...,4939656,4631585.52,WhiteWhiteSilverBlackRedSpace GrayBlackBlueRed...,1TB128GB512GB2TB2TB64GB256GB64GB128GB2TB64GB64...,16GB6GB16GB32GB6GB6GB16GB6GB32GB6GB4GB8GB8GB6G...,M1M3A14 BionicM2M1M2M2M1M2M1A16 BionicM1A16 Bi...,M-Series GPUIntegratedM-Series GPUIntegratedAp...,"13.3""13.3""6.7""6.1""6.7""14""16""10.2""16""16""14""6.7""...",16351321,3961789,232x245x22172x299x5128x73x3668x71x1080x243x342...,2 Years6 Months6 Months1 Year1 Year2 Years1 Ye...,GermanyUSAUKUSAIndiaIndiaChinaChinaUSAGermanyG...,S6005S9436S4182S7923S8965S7470S9975S6175S6014S...,2055,6149686
2.9,P000003P000029P000035P000058P000078P000093P000...,MacBookiPhoneApple WatchiMaciPadiPadiPhoneiPho...,Model-125Model-818Model-384Model-370Model-146M...,4856903,4567222.73,SilverSilverWhiteWhiteBlackBlueBlackWhiteRedGo...,1TB512GB128GB2TB2TB128GB64GB1TB64GB128GB1TB512...,16GB8GB6GB6GB6GB16GB16GB32GB4GB16GB32GB32GB32G...,A15 BionicA14 BionicM3A15 BionicA14 BionicA15 ...,M-Series GPUIntegratedApple GPUApple GPUApple ...,"5.4""6.1""6.1""16""6.7""6.7""13.3""13.3""6.7""6.1""5.4""1...",16359025,3878172,220x150x3181x117x5121x292x13372x184x24373x66x2...,2 Years1 Year6 Months1 Year1 Year6 Months2 Yea...,IndiaIndiaIndiaUSAIndiaChinaJapanChinaUKChinaG...,S9930S9751S1543S2600S4477S9032S8064S3497S1597S...,2036,5973536
3.0,P000122P000162P000254P000259P000262P000370P000...,iPhoneiPadMacBookiMaciPadiMacAirPodsMacBookiMa...,Model-894Model-873Model-371Model-316Model-847M...,5056638,4763560.32,GoldWhiteWhiteBlackSilverRedRedWhiteRedBlackSi...,64GB1TB128GB32GB1TB512GB32GB512GB128GB512GB32G...,16GB16GB32GB4GB6GB4GB4GB16GB6GB8GB4GB32GB32GB4...,M2A15 BionicA14 BionicM3A14 BionicA14 BionicA1...,Apple GPUApple GPUM-Series GPUM-Series GPUAppl...,"16""6.7""6.1""10.2""5.4""10.2""5.4""16""10.2""16""5.4""16...",16982246,4035705,68x195x39173x109x10210x254x37104x138x27182x283...,6 Months1 Year1 Year2 Years6 Months6 Months1 Y...,USAUKChinaGermanyIndiaJapanIndiaIndiaUSAUSAUSA...,S5806S2674S8475S6894S3255S6311S5747S9501S8110S...,2121,6227607
3.1,P000025P000053P000084P000089P000097P000106P000...,Apple WatchiPadApple WatchAirPodsiMaciMaciPhon...,Model-674Model-199Model-975Model-384Model-314M...,5064652,4788271.04,BlueSilverRedRedSpace GrayRedSpace GrayRedWhit...,1TB32GB2TB512GB512GB1TB32GB64GB512GB512GB2TB2T...,16GB32GB6GB4GB6GB4GB4GB4GB4GB32GB32GB32GB32GB6...,A14 BionicM3M3A14 BionicM1M1M2M3A15 BionicM2M1...,M-Series GPUM-Series GPUIntegratedApple GPUApp...,"14""6.7""10.2""14""16""6.1""6.1""6.1""14""10.2""6.1""16""1...",16871013,4070454,139x216x25224x149x21295x94x16366x200x28259x248...,1 Year1 Year2 Years2 Years6 Months6 Months6 Mo...,ChinaUKChinaUSAIndiaUSAIndiaIndiaGermanyJapanC...,S8623S3015S4640S6191S2221S8341S3353S4447S3652S...,2127,6327179
3.2,P000030P000060P000061P000155P000207P000217P000...,MacBookiMaciMaciMaciMaciPhoneiPhoneiPhoneMacBo...,Model-658Model-144Model-847Model-508Model-208M...,5105303,4778511.54,RedWhiteBlueRedSilverWhiteSpace GrayRedRedSpac...,512GB256GB2TB128GB32GB512GB1TB128GB64GB256GB1T...,4GB4GB16GB32GB8GB16GB6GB32GB4GB32GB16GB4GB8GB4...,M2M1M3M3A14 BionicA14 BionicA15 BionicA15 Bion...,Apple GPUIntegratedIntegratedM-Series GPUApple...,"10.2""14""5.4""5.4""16""5.4""5.4""5.4""5.4""13.3""14""10....",17063407,4025328,199x176x11390x99x29115x215x19161x139x12107x271...,1 Year1 Year2 Years1 Year1 Year1 Year2 Years6 ...,USAIndiaGermanyJapanGermanyUKIndiaJapanUKChina...,S4449S3386S4001S6915S4082S4447S8144S8399S9661S...,2170,6396757
3.3,P000010P000024P000027P000038P000067P000113P000...,AirPodsiPadiMacMacBookiPadMacBookMacBookiPhone...,Model-204Model-127Model-833Model-106Model-665M...,5141436,4806477.49,GoldGoldBlueGoldWhiteGoldSilverBlackSpace Gray...,1TB64GB32GB256GB64GB256GB2TB512GB128GB128GB64G...,4GB32GB4GB4GB16GB4GB8GB16GB6GB8GB8GB32GB32GB8G...,M3A15 BionicM2A15 BionicA14 BionicM1A16 Bionic...,IntegratedIntegratedApple GPUIntegratedM-Serie...,"6.1""6.7""10.2""13.3""5.4""10.2""14""6.7""16""5.4""6.1""5...",17263838,4006509,149x196x9200x143x37304x113x2061x87x10320x214x3...,6 Months1 Year6 Months1 Year6 Months6 Months6 ...,UKGermanyIndiaUSAJapanGermanyChinaJapanUSAGerm...,S1232S5307S8538S7955S8795S8436S1057S3708S8026S...,2162,6210928
3.4,P000005P000065P000111P000154P000181P000183P000...,AirPodsiPhoneMacBookAirPodsiPhoneMacBookiPhone...,Model-381Model-487Model-573Model-697Model-981M...,5123467,4832900.88,BlueBlueSpace GrayBlueWhiteWhiteBlueSilverSilv...,512GB512GB32GB512GB512GB32GB64GB512GB2TB512GB3...,4GB8GB16GB6GB16GB16GB8GB4GB16GB6GB6GB32GB16GB1...,A15 BionicA15 BionicM3A15 BionicA14 BionicM1A1...,Apple GPUIntegratedApple GPUIntegratedIntegrat...,"13.3""13.3""13.3""16""6.1""14""16""10.2""14""6.7""6.1""14...",17069447,4015722,276x164x5378x271x24322x135x40270x281x3293x229x...,2 Years1 Year6 Months6 Months1 Year1 Year6 Mon...,ChinaUSAUKUKChinaIndiaUKJapanJapanUSAIndiaUKIn...,S4957S3144S7756S2253S3613S9359S6100S8088S8287S...,2131,6396904
3.5,P000002P000032P000216P000218P000247P000280P000...,AirPodsiPadMacBookiPadApple WatchApple WatchiM...,Model-214Model-325Model-256Model-880Model-884M...,5091291,4834918.23,RedSilverSpace GraySpace GraySpace GraySpace G...,1TB128GB512GB64GB128GB1TB32GB64GB1TB2TB32GB64G...,4GB6GB32GB6GB6GB4GB32GB6GB8GB32GB32GB8GB6GB6GB...,A14 BionicM1A14 BionicM1M3M2M3A15 BionicM1M1M2...,M-Series GPUIntegratedIntegratedIntegratedM-Se...,"6.1""6.1""16""6.1""10.2""5.4""16""10.2""5.4""14""16""16""1...",17034580,4011735,153x102x38137x120x23389x281x30163x297x25189x25...,1 Year2 Years1 Year6 Months1 Year2 Years2 Year...,USAGermanyGermanyIndiaJapanUSAChinaIndiaJapanU...,S6264S4247S9555S7745S9783S2550S1477S5751S6314S...,2136,6226496
3.6,P000012P000015P000051P000088P000123P000163P000...,MacBookiPadApple WatchApple WatchApple WatchAi...,Model-858Model-704Model-194Model-489Model-157M...,4893566,4695151.60,BlackBlackGoldBlackSilverGoldBlueBlueSpace Gra...,1TB128GB256GB32GB512GB128GB1TB512GB2TB64GB256G...,16GB6GB8GB6GB16GB16GB4GB6GB8GB4GB32GB32GB8GB32...,M3A16 BionicM1A16 BionicM2A14 BionicM3A14 Bion...,Apple GPUIntegratedM-Series GPUM-Series GPUM-S...,"6.1""6.7""6.7""16""10.2""14""6.1""6.1""13.3""10.2""14""5....",16589179,3905369,97x65x14104x127x34248x80x21130x136x1060x282x32...,1 Year1 Year1 Year6 Months2 Years1 Year2 Years...,GermanyIndiaChinaChinaChinaChinaIndiaGermanyCh...,S9646S3294S9719S6928S7279S1484S9098S3913S7150S...,2054,6107237

In [14]:
df[df["color"] == "Silver"][["release_year", "price", "country_origin"]]

       release_year    price country_origin
2              2016  1877.50          India
3              2019  1475.74            USA
12             2021   315.34          Japan
16             2024  1901.43             UK
28             2019  2404.75          India
...             ...      ...            ...
99927          2020  1849.83        Germany
99958          2016  2679.17          China
99972          2024  3143.80          China
99980          2021  1712.75        Germany
99987          2016  2160.07          Japan

[14207 rows x 3 columns]

In [19]:
df.groupby("country_origin")["price"].sum()

country_origin
China      31678547.89
Germany    31811983.62
India      31868593.56
Japan      31885047.89
UK         31171660.93
USA        31811975.90
Name: price, dtype: float64

In [21]:
df.groupby(["country_origin", "ram"])["price"].sum()

country_origin  ram
China           16GB    6274287.01
                32GB    6489954.72
                4GB     6442376.22
                6GB     6216692.72
                8GB     6255237.22
Germany         16GB    6331758.78
                32GB    6341549.23
                4GB     6337218.16
                6GB     6386520.91
                8GB     6414936.54
India           16GB    6234381.66
                32GB    6495273.22
                4GB     6535414.81
                6GB     6326025.18
                8GB     6277498.69
Japan           16GB    6435665.92
                32GB    6332787.64
                4GB     6426877.24
                6GB     6234849.82
                8GB     6454867.27
UK              16GB    6295284.65
                32GB    5941868.69
                4GB     6286563.31
                6GB     6270398.60
                8GB     6377545.68
USA             16GB    6632884.19
                32GB    6346666.24
                4GB     6369137.16
                6GB     6122541.39
                8GB     6340746.92
Name: price, dtype: float64

In [34]:
df.groupby(["country_origin","ram"]).agg({"price":["sum", "max", "min"], "weight_grams":["mean", "std"]})

                          price                  weight_grams
                            sum      max     min         mean         std
country_origin ram
China          16GB  6274287.01  3499.74  300.23  1595.866404  809.194735
               32GB  6489954.72  3499.88  303.12  1559.135828  799.088907
               4GB   6442376.22  3499.05  300.07  1621.084352  814.547372
               6GB   6216692.72  3498.31  300.28  1607.020120  814.148519
               8GB   6255237.22  3498.73  300.19  1602.149618  814.240590
Germany        16GB  6331758.78  3498.74  301.31  1612.591346  814.776407
               32GB  6341549.23  3498.63  300.17  1620.881602  807.812555
               4GB   6337218.16  3497.71  300.54  1621.980024  796.409815
               6GB   6386520.91  3499.50  301.30  1598.142857  801.233362
               8GB   6414936.54  3498.62  302.30  1591.251355  804.740984
India          16GB  6234381.66  3499.87  300.68  1579.379705  810.990394
               32GB  6495273.22  3499.85  301.12  1584.694069  808.787742
               4GB   6535414.81  3499.81  300.31  1604.502511  805.379789
               6GB   6326025.18  3499.91  301.15  1584.883894  799.277469
               8GB   6277498.69  3499.44  300.11  1593.219549  796.582227
Japan          16GB  6435665.92  3499.36  301.25  1608.747204  814.511393
               32GB  6332787.64  3499.51  301.22  1584.195698  806.560225
               4GB   6426877.24  3499.62  300.33  1592.018446  804.453014
               6GB   6234849.82  3497.56  300.83  1568.092138  807.997585
               8GB   6454867.27  3498.02  300.06  1603.872461  798.361955
UK             16GB  6295284.65  3497.54  301.55  1587.829290  802.928063
               32GB  5941868.69  3499.69  300.07  1613.571030  807.777586
               4GB   6286563.31  3499.47  300.10  1614.738443  810.615015
               6GB   6270398.60  3499.22  300.58  1591.355502  807.444222
               8GB   6377545.68  3498.06  302.31  1596.609047  808.139179
USA            16GB  6632884.19  3499.58  300.03  1601.411748  813.233201
               32GB  6346666.24  3499.87  301.35  1612.660147  810.440234
               4GB   6369137.16  3499.01  301.94  1598.751269  810.753704
               6GB   6122541.39  3499.95  303.58  1610.966606  822.170997
               8GB   6340746.92  3499.00  300.11  1588.551405  805.409789