In [1]:
import numpy as np
import pandas as pd

In [7]:
data = pd.read_csv('IPL_Squad_2023_Auction_Dataset.csv')
data.sample(5)

,Unnamed: 0,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
402,402,Manav Suthar,2000000,BOWLER,NaN,NaN,NaN,Unsold
108,108,Nathan Ellis,Retained,BOWLER,0.0,0.0,PBKS,Punjab Super Kings
538,538,Deepesh Nailwal,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
237,237,Fazalhaq Farooqi,Retained,BOWLER,0.0,0.0,SRH,Sunrisers Hyderabad
139,139,K. Gowtham,Retained,ALL-ROUNDER,0.0,0.0,LSG,Lucknow Super Giants

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       568 non-null    int64
 1   Player's List    568 non-null    object
 2   Base Price       568 non-null    object
 3   TYPE             568 non-null    object
 4   COST IN ₹ (CR.)  243 non-null    float64
 5   Cost IN $ (000)  243 non-null    float64
 6   2022 Squad       230 non-null    object
 7   Team             568 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 35.6+ KB

In [6]:
data.describe()

       Unnamed: 0  COST IN ₹ (CR.)  Cost IN $ (000)
count  568.000000       243.000000       243.000000
mean   283.500000         0.687243        82.469136
std    164.111751         2.511700       301.404032
min      0.000000         0.000000         0.000000
25%    141.750000         0.000000         0.000000
50%    283.500000         0.000000         0.000000
75%    425.250000         0.200000        24.000000
max    567.000000        18.500000      2220.000000

In [8]:
# Step 1: Drop unnecessary column
data.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
# Step 2: Clean 'Base Price'

# Replace 'Retained' with 0
data['Base Price'] = data['Base Price'].replace('Retained', 0)

# Convert to numeric
data['Base Price'] = pd.to_numeric(data['Base Price'])

In [10]:
# Step 3: Fill missing values in cost columns with 0
data['COST IN ₹ (CR.)'] = data['COST IN ₹ (CR.)'].fillna(0)
data['Cost IN $ (000)'] = data['Cost IN $ (000)'].fillna(0)

In [11]:
# Step 4: Fill missing values in '2022 Squad'
data['2022 Squad'] = data['2022 Squad'].fillna('Not in 2022 Squad')

In [12]:
# Step 5: Final null check
data.isnull().sum()

Player's List      0
Base Price         0
TYPE               0
COST IN ₹ (CR.)    0
Cost IN $ (000)    0
2022 Squad         0
Team               0
dtype: int64

In [13]:
# Step 6: One-hot encoding categorical columns
data = pd.get_dummies(data, columns=['TYPE', 'Team'], drop_first=True)

In [14]:
# Step 7: Final dataset info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Player's List                    568 non-null    object
 1   Base Price                       568 non-null    int64
 2   COST IN ₹ (CR.)                  568 non-null    float64
 3   Cost IN $ (000)                  568 non-null    float64
 4   2022 Squad                       568 non-null    object
 5   TYPE_BATSMAN                     568 non-null    bool
 6   TYPE_BOWLER                      568 non-null    bool
 7   TYPE_WICKETKEEPER                568 non-null    bool
 8   Team_Delhi Capitals              568 non-null    bool
 9   Team_Gujarat Titans              568 non-null    bool
 10  Team_Kolkata Knight Riders       568 non-null    bool
 11  Team_Lucknow Super Giants        568 non-null    bool
 12  Team_Mumbai Indians              568 non-null    bool
 13  Team_Punjab Super Kings          568 non-null    bool
 14  Team_Rajasthan Royals            568 non-null    bool
 15  Team_Royal Challengers Banglore  568 non-null    bool
 16  Team_Sunrisers Hyderabad         568 non-null    bool
 17  Team_Unsold                      568 non-null    bool
dtypes: bool(13), float64(2), int64(1), object(2)
memory usage: 29.5+ KB

In [15]:
data.to_csv("cleaned_IPL_2023_dataset.csv", index=False)