In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("covid.csv")
df

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,NaN,1.0,NaN,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,NaN,NaN,NaN,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3.489000e+03,13,NaN,NaN,NaN,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,8.010000e+02,12,NaN,NaN,NaN,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,NaN,1.0,NaN,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

In [3]:
df.head()

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF

In [4]:
df.tail()

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
204,Montserrat,North America,4992.0,13,NaN,1.0,NaN,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,26247.0,13,NaN,NaN,NaN,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3489.0,13,NaN,NaN,NaN,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,801.0,12,NaN,NaN,NaN,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,598682.0,10,NaN,1.0,NaN,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country/Region    209 non-null    object
 1   Continent         208 non-null    object
 2   Population        208 non-null    float64
 3   TotalCases        209 non-null    int64
 4   NewCases          4 non-null      float64
 5   TotalDeaths       188 non-null    float64
 6   NewDeaths         3 non-null      float64
 7   TotalRecovered    205 non-null    float64
 8   NewRecovered      3 non-null      float64
 9   ActiveCases       205 non-null    float64
 10  Serious,Critical  122 non-null    float64
 11  Tot Cases/1M pop  208 non-null    float64
 12  Deaths/1M pop     187 non-null    float64
 13  TotalTests        191 non-null    float64
 14  Tests/1M pop      191 non-null    float64
 15  WHO Region        184 non-null    object
 16  iso_alpha         209 non-null    object
dtypes: float64(12), int64(1), object(4)
memory usage: 27.9+ KB

In [6]:
df.describe()

,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop
count,2.080000e+02,2.090000e+02,4.000000,188.000000,3.000000,2.050000e+02,3.000000,2.050000e+02,122.000000,208.000000,187.000000,1.910000e+02,191.000000
mean,3.041549e+07,9.171850e+04,1980.500000,3792.590426,300.000000,5.887898e+04,1706.000000,2.766433e+04,534.393443,3196.024038,98.681176,1.402405e+06,83959.366492
std,1.047661e+08,4.325867e+05,3129.611424,15487.184877,451.199512,2.566984e+05,2154.779803,1.746327e+05,2047.518613,5191.986457,174.956862,5.553367e+06,152730.591240
min,8.010000e+02,1.000000e+01,20.000000,1.000000,1.000000,7.000000e+00,42.000000,0.000000e+00,1.000000,3.000000,0.080000,6.100000e+01,4.000000
25%,9.663140e+05,7.120000e+02,27.500000,22.000000,40.500000,3.340000e+02,489.000000,8.600000e+01,3.250000,282.000000,6.000000,2.575200e+04,8956.500000
50%,7.041972e+06,4.491000e+03,656.000000,113.000000,80.000000,2.178000e+03,936.000000,8.990000e+02,27.500000,1015.000000,29.000000,1.357020e+05,32585.000000
75%,2.575614e+07,3.689600e+04,2609.000000,786.000000,449.500000,2.055300e+04,2538.000000,7.124000e+03,160.250000,3841.750000,98.000000,7.576960e+05,92154.500000
max,1.381345e+09,5.032179e+06,6590.000000,162804.000000,819.000000,2.576668e+06,4140.000000,2.292707e+06,18296.000000,39922.000000,1238.000000,6.313960e+07,995282.000000

In [7]:
df.describe(include="O")

       Country/Region Continent WHO Region iso_alpha
count             209       208        184       209
unique            209         6          6       193
top               USA    Africa     Europe
freq                1        57         55        10

In [8]:
df.columns

Index(['Country/Region', 'Continent', 'Population', 'TotalCases', 'NewCases',
       'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered',
       'ActiveCases', 'Serious,Critical', 'Tot Cases/1M pop', 'Deaths/1M pop',
       'TotalTests', 'Tests/1M pop', 'WHO Region', 'iso_alpha'],
      dtype='object')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Country/Region        0
Continent             1
Population            1
TotalCases            0
NewCases            205
TotalDeaths          21
NewDeaths           206
TotalRecovered        4
NewRecovered        206
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      1
Deaths/1M pop        22
TotalTests           18
Tests/1M pop         18
WHO Region           25
iso_alpha             0
dtype: int64

In [13]:
df['Population'] = df['Population'].fillna(df['Population'].median())

In [14]:
df['Continent'] = df['Continent'].fillna(df['Continent'].mode()[0])

In [15]:
df['WHO Region'] = df['WHO Region'].fillna(df['WHO Region'].mode()[0])

In [16]:
df['TotalDeaths'] = df['TotalDeaths'].fillna(df['TotalDeaths'].median())

In [17]:
df['TotalRecovered'] = df['TotalRecovered'].fillna(df['TotalRecovered'].median())

In [18]:
df['ActiveCases'] = df['ActiveCases'].fillna(df['ActiveCases'].median())

In [19]:
df['Serious,Critical'] = df['Serious,Critical'].fillna(df['Serious,Critical'].median())

In [20]:
df['Tot Cases/1M pop'] = df['Tot Cases/1M pop'].fillna(df['Tot Cases/1M pop'].median())

In [21]:
df['Deaths/1M pop'] = df['Deaths/1M pop'].fillna(df['Deaths/1M pop'].median())

In [22]:
df['TotalTests'] = df['TotalTests'].fillna(df['TotalTests'].median())

In [23]:
df['Tests/1M pop'] = df['Tests/1M pop'].fillna(df['Tests/1M pop'].median())

In [24]:
# For 'NewCases', 'NewDeaths', 'NewRecovered', we can fill these with 0 for simplicity
df['NewCases'] = df['NewCases'].fillna(0)
df['NewDeaths'] = df['NewDeaths'].fillna(0)
df['NewRecovered'] = df['NewRecovered'].fillna(0)

In [25]:
# Step 2: Drop columns with excessive missing data if necessary
# Here, we drop 'Serious,Critical' as it has 87 missing values, which is too high.
df.drop(columns=['Serious,Critical'], inplace=True)

In [26]:
# One-Hot Encoding for categorical columns like 'Continent', 'WHO Region', etc.
df = pd.get_dummies(df, columns=['Continent', 'WHO Region'], drop_first=True)

In [27]:
df.isnull().sum()

Country/Region                     0
Population                         0
TotalCases                         0
NewCases                           0
TotalDeaths                        0
NewDeaths                          0
TotalRecovered                     0
NewRecovered                       0
ActiveCases                        0
Tot Cases/1M pop                   0
Deaths/1M pop                      0
TotalTests                         0
Tests/1M pop                       0
iso_alpha                          0
Continent_Asia                     0
Continent_Australia/Oceania        0
Continent_Europe                   0
Continent_North America            0
Continent_South America            0
WHO Region_Americas                0
WHO Region_EasternMediterranean    0
WHO Region_Europe                  0
WHO Region_South-EastAsia          0
WHO Region_WesternPacific          0
dtype: int64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country/Region                   209 non-null    object
 1   Population                       209 non-null    float64
 2   TotalCases                       209 non-null    int64
 3   NewCases                         209 non-null    float64
 4   TotalDeaths                      209 non-null    float64
 5   NewDeaths                        209 non-null    float64
 6   TotalRecovered                   209 non-null    float64
 7   NewRecovered                     209 non-null    float64
 8   ActiveCases                      209 non-null    float64
 9   Tot Cases/1M pop                 209 non-null    float64
 10  Deaths/1M pop                    209 non-null    float64
 11  TotalTests                       209 non-null    float64
 12  Tests/1M pop                     209 non-null    float64
 13  iso_alpha                        209 non-null    object
 14  Continent_Asia                   209 non-null    bool
 15  Continent_Australia/Oceania      209 non-null    bool
 16  Continent_Europe                 209 non-null    bool
 17  Continent_North America          209 non-null    bool
 18  Continent_South America          209 non-null    bool
 19  WHO Region_Americas              209 non-null    bool
 20  WHO Region_EasternMediterranean  209 non-null    bool
 21  WHO Region_Europe                209 non-null    bool
 22  WHO Region_South-EastAsia        209 non-null    bool
 23  WHO Region_WesternPacific        209 non-null    bool
dtypes: bool(10), float64(11), int64(1), object(2)
memory usage: 25.0+ KB